### ISSUE TITLE
Allow to apply $removeparam rules to all resources

### ISSUE THREAD

**Issue by tvinzz** [AdguardTeam/tsurlfilter#33] opened 2021-08-30 21:27 UTC
Issue made by @AdamWr and moved here from FiltersCompiler repo
https://github.com/AdguardTeam/FiltersCompiler/issues/115

**Comment by Mizzick** [comment] 2021-09-14 09:53
duplicate of #16

**Closed by Mizzick** 2021-09-14 09:53 UTC
Labels: Version: AdGuard v4.0
