### ISSUE TITLE
Support uBO's matches-media

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/tsurlfilter#81] opened 2023-04-11 15:32 UTC
Inverse of https://github.com/AdguardTeam/FiltersCompiler/issues/175

**Comment by ameshkov** [comment] 2023-04-11 15:37
@maximtop possible implementations:

1. Support it uBO-like, i.e. natively (parse the rule, check if there's `:matches-media`, take it into account when composing a rule).
2. Via rules converter

Tbh, I am not sure which one is better.

Also, we should definitely file it to CoreLibs as well.

**Comment by ameshkov** [comment] 2023-04-14 14:15
Appears to be duplicate of https://github.com/AdguardTeam/tsurlfilter/issues/70

**Closed by ameshkov** 2023-04-14 14:15 UTC
Labels: enhancement, Version: AdGuard v4.3
